<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PartyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartyRepository extends EntityRepository
{
    public function findUniqueCities()
    {
        return $this->getEntityManager()->getRepository('AppBundle:Party')
            ->createQueryBuilder('p')
            ->select('p.city')
            ->distinct(true)
            ->getQuery()
            ->getResult();
    }
}
